#!/bin/sh
set -e
fail() {
  echo "$@" 1>&2
  exit 1
}
if [ $# != 1 ]
then
  fail 'Usage: wav2fzv INFILE'
fi
tmp=$(mktemp)
if [ $? != 0 ]
then
  fail 'mktemp failed'
fi
trap "rm -f \"$tmp\"" exit
sox -G "$1" -t s16 -L "$tmp" rate -v 36000 pad 0 8s
size=$(ls -l "$tmp" | awk '{print $6}')
if [ $? != 0 ]
then
  fail 'wc failed'
fi
awk -v size="$size" '
END {
  samples = size/2
  Long(0) # wave start
  Long(samples) # wave end
  Long(0) # gen start
  Long(samples-8) # gen end
  Int(0) # loop sus, loop end
  Long(471) # normal sample playback
  for(i=1;i<=16;i++) Long(samples-8) # loop start, loop end
  for(i=1;i<=8;i++) Int(0) # loop crossfade
  for(i=1;i<=8;i++) Int(100) # loop time
}
function Long(x) {
  printf "%c%c%c%c", int(x), int(x/256), int(x/65536), int(x/16777216)
}
function Int(x) {
  printf "%c%c", int(x), int(x/256)
}
' /dev/null
